apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatrice-deployment
  labels:
    app: calculatrice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculatrice
  template:
    metadata:
      labels:
        app: calculatrice
    spec:
      containers:
      - name: calculatrice
        image: zavarcedrick/calculatrice:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: calculatrice-service
spec:
  type: LoadBalancer
  selector:
    app: calculatrice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
